from __future__ import annotations

import contextlib
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

from pygenkit.generators.base import BaseGenerator
from pygenkit.models.config import PyGenKitConfig
from pygenkit.utils.filters import TemplateFilters


class ProjectGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__("project")

    def generate(
        self,
        name: str,
        output_dir: str | Path = ".",
        force: bool = False,
        author_name: str = "",
        author_email: str = "",
        github_owner: str = "",
        description: str = "",
        version: str = "0.1.0",
    ) -> Path:
        root = Path(output_dir).resolve() / name
        if root.exists() and not force:
            msg = f"{root} already exists. Use --force to overwrite."
            raise FileExistsError(msg)

        module_name = TemplateFilters.snake_case(name)
        author_name = author_name or _git_config("user.name") or "Your Name"
        author_email = author_email or _git_config("user.email") or "your@email.com"
        github_owner = github_owner or _git_config("github.user") or "your-username"
        description = description or f"{name} — generated by PyGenKit"
        year = datetime.now().year

        ctx: dict[str, Any] = {
            "project": {
                "name": name,
                "version": version,
                "description": description,
            },
            "module_name": module_name,
            "author": {
                "name": author_name,
                "email": author_email,
            },
            "github": {
                "owner": github_owner,
            },
            "year": year,
        }

        files: list[tuple[str, str]] = [
            ("src/__init__.py", f"src/{module_name}/__init__.py"),
            ("src/cli.py", f"src/{module_name}/cli.py"),
            ("tests/__init__.py", "tests/__init__.py"),
            ("tests/test_cli.py", "tests/test_cli.py"),
            ("pyproject.toml", "pyproject.toml"),
            ("README.md", "README.md"),
            ("LICENSE", "LICENSE"),
            (".gitignore", ".gitignore"),
            (".editorconfig", ".editorconfig"),
            (".pre-commit-config.yaml", ".pre-commit-config.yaml"),
        ]

        for template_rel, output_rel in files:
            out = root / output_rel
            out.parent.mkdir(parents=True, exist_ok=True)
            self.render(template_rel + ".j2", root, output_rel, ctx, force=True)

        _generate_pygenkit_toml(root, name, github_owner)

        _run_commands(root)

        return root


def _git_config(key: str) -> str:
    try:
        r = subprocess.run(
            ["git", "config", "--global", key],
            capture_output=True, text=True, timeout=5,
        )
        return r.stdout.strip() if r.returncode == 0 else ""
    except (subprocess.SubprocessError, FileNotFoundError):
        return ""


def _generate_pygenkit_toml(root: Path, name: str, github_owner: str) -> None:
    content = PyGenKitConfig.generate_default(name)
    toml_path = root / "pygenkit.toml"
    toml_path.write_text(content, encoding="utf-8")

    if github_owner and github_owner != "your-username":
        raw = toml_path.read_text(encoding="utf-8")
        raw = raw.replace('owner = ""', f'owner = "{github_owner}"')
        toml_path.write_text(raw, encoding="utf-8")


def _run_commands(root: Path) -> None:
    with contextlib.suppress(subprocess.SubprocessError, FileNotFoundError):
        subprocess.run(
            ["git", "init"],
            cwd=str(root), capture_output=True, timeout=10,
        )
