from __future__ import annotations

from pathlib import Path


def create_project(name: str, cwd: str | Path | None = None) -> Path:
    base_dir = Path(cwd or ".").resolve() / name
    base_dir.mkdir(parents=True, exist_ok=True)

    (base_dir / "src" / _module_name(name)).mkdir(parents=True, exist_ok=True)
    (base_dir / "tests").mkdir(parents=True, exist_ok=True)

    (base_dir / "pyproject.toml").write_text(_pyproject_content(name), encoding="utf-8")
    (base_dir / "README.md").write_text(_readme_content(name), encoding="utf-8")
    (base_dir / "src" / _module_name(name) / "__init__.py").write_text(
        '"""Package for {name}."""\n'.format(name=name),
        encoding="utf-8",
    )
    (base_dir / "src" / _module_name(name) / "cli.py").write_text(
        'def main():\n    print("Hello from PyGenesis!")\n',
        encoding="utf-8",
    )

    return base_dir


def _module_name(name: str) -> str:
    return name.replace("-", "_")


def _pyproject_content(name: str) -> str:
    return f"""[project]\nname = \"{name}\"\nversion = \"0.1.0\"\ndescription = \"Generated by pygenesis\"\nrequires-python = \">=3.9\"\n\n[build-system]\nrequires = [\"setuptools>=68\"]\nbuild-backend = \"setuptools.build_meta\"\n\n[tool.setuptools]\npackage-dir = {{\"\" = \"src\"}}\n\n[tool.setuptools.packages.find]\nwhere = [\"src\"]\n"""


def _readme_content(name: str) -> str:
    return f"# {name}\n\nGenerated by pygenesis.\n"
